### ISSUE TITLE
Pitch accent of compound words?

### ISSUE THREAD

**Issue by archiif** [mifunetoshiro/kanjium#14]
Is there any way to access the multiple pitch accents of compound words?

For example, with 一子相伝, this is what is displayed in the NHK pitch accent dictionary:
![image](https://user-images.githubusercontent.com/60074051/111704789-475f2880-8872-11eb-93dc-83fc56ed662f.png)

And this is the data in `accents.txt`:

```
term     reading	accents
一子相伝  いっしそうでん  1,0
```

So, is there any way to at least know that the word actually consists of multiple pitch accents?

**Comment by mifunetoshiro** [comment]
Checking for a comma (,) with a script should give you a list of words with multiple pitch accents.

**Comment by arjunsatarkar** [comment]
It seems like when there is a comma sometimes it means there are multiple accepted variants and sometimes it means the word is a compound which includes multiple accent patterns, so that is unfortunately ambiguous. Still, the lines with no commas should all be usable, which is most of them.
