### ISSUE TITLE
Question regarding source of pitch accent data

### ISSUE THREAD

**Issue by molesquirrel** [mifunetoshiro/kanjium#15]
Hello, 

I wanted to see if I could get some clarity on the source of the pitch accent data provided with this repo. The readme references a "free database by Uros O", but I am unclear as to if this free database is this very repo, or if it is referring to another database.

If it's another database, I'd love to know where it is located. The reason for this is that I'd like to look up the original license for the data, as well as look into how the data was generated, what rules were followed, marking regarding the pitch drop following the ends of words in a sentence, etc.

Thanks!

**Comment by x0rnn** [comment]
I maybe worded it badly, but only the CSS/arrow pitch accent notation was meant in that context. See issue #13

**Comment by mifunetoshiro** [comment]
I maybe worded it wrong, but only the CSS/arrow pitch accent notation was meant in that context.

See issue #13.
