### ISSUE TITLE
戸 specified as radical for several kanji instead of 戶in the kanjidict table

### ISSUE THREAD

**Issue by nibarius** [mifunetoshiro/kanjium#3]
In the kanjidict table the kanji: "戸", "所", "扇", "扉", "房", "戻", "扈", "戾" are said to have the radical 戸. However 戸 does not exist as a radical in the radicals table, it only exists as a "radvar" for 戶.

Shouldn't these kanji all use the 戶 radical instead since that's the real radical?

(The kanji 戶 is the only one that lists 戶 as it's radical in kanjidict)

**Comment by mifunetoshiro** [comment]
Indeed, thanks.
