### ISSUE TITLE
Additional phonetics

### ISSUE THREAD

**Issue by kishimoto-tsuneyo** [mifunetoshiro/kanjium#5]
Here are Japanese kanji phonetic components from _Remembering the Kanji_ that are not present in the `phonetics` table:

```
卜刃冊厉弗句㐱争杀丞曳危后赫亜困助貝匊蚤帛阜昏奄炎冥発畏馬扇準芻郭康虚御筑殿爾
```

Some of these produce groups of only two, but others (like `杀`) have several members.

**Comment by kishimoto-tsuneyo** [comment]
Also, phonetic `専` should be changed to `尃` for these kanji: `博薄縛`.

**Comment by mifunetoshiro** [comment]
I've only included phonetics that have at least 2 members (including itself) that are either jōyō or jinmeiyō. Does this apply for any of these? Could you provide RTK2/3 numbers, or even better, all their members? Thanks.

**Comment by kishimoto-tsuneyo** [comment]
Thanks—it helps to know the criteria. (I did not see it documented anywhere.) I will review _RTK_ and report back.

How did you collect data to create your phonetic groups? Does `痣` qualify to be in your `士` group?

**Comment by mifunetoshiro** [comment]
No, because it's a hyōgaiji. If I were to include hyōgaiji, the phonetic data would probably be 2x bigger. As for 尃, you are right, I think I just used 専 for simplicity's sake.

I couldn't check 杀, 㐱, 厉 (so if you could list just kanji with those 3 phonetics it would be great), but I could add 爾, 筑, 隼, 畏, 昏, 匊, 丞, 弗, 冊, 卜.

**Comment by kishimoto-tsuneyo** [comment]
OK, thanks for clarifying that hyōgaiji are excluded from the phonetics.

I won't check _RTK_ (I don't have time right now) but if there's anything you need me to verify, let me know. I have a lot of kanji reference resources.

**Comment by mifunetoshiro** [comment]
It would, yes, but it would also complicate matters with a huge number of phonetics that would now have multiple possible readings, etc. Anyway, I've added more phonetics now.
