### ISSUE TITLE
Missing kanji: 丫

### ISSUE THREAD

**Issue by kishimoto-tsuneyo** [mifunetoshiro/kanjium#6]
`丫` has Japanese readings ア and あげまき.

面区点: 2-01-06
Unicode: U+4E2B

**Comment by mifunetoshiro** [comment]
There are thousands of kanji from JIS X 0213 missing, why include this one in particular?

**Comment by kishimoto-tsuneyo** [comment]
I mention `丫` because it's the first entry in the official 漢検 dictionary, which categorizes it as a 1级 kanji.

This issue is effectively a duplicate of #7, so I will close it.
