### ISSUE TITLE
Inaccurate kanken data

### ISSUE THREAD

**Issue by kishimoto-tsuneyo** [mifunetoshiro/kanjium#7]
The `kanjidict` table has 6505 `kanken` kanji:
```
SELECT count(kanji) FROM kanjidict WHERE kanken IS NOT NULL;
⇒ 6505
```

However the official 漢検 kanji dictionary only has 5647 distinct kanji plus 642 _kyujitai_ (for 6289 total kanji).

**Comment by mifunetoshiro** [comment]
I believe these extra ones are all kanken level 1 国字, I can't remember the source, but it listed them as 1級.
