### ISSUE TITLE
Jukugo frequency list

### ISSUE THREAD

**Issue by Fandekasp** [mifunetoshiro/kanjium#8]
hi @mifunetoshiro

brief introduction: 30yo french software engineer living in Japan 6 years, got jlpt n3 a couple years ago, very bad with kanji learning, working in a japanese company somewhat communicating at business level. Tried many times to learn Kanji, and forgot them quickly as soon as I'd stop for a while (mnemonic-based, radicals+mnemonics, etymology+radicals+mnemonics).

From my experience with kanji learning, I understand that there are 3 schools of learning kanjis:
* The japanese scholar way: rote learning by repetition
* The foreigner way: learning by mnemonics aka fake stories to make the shape & sound memorable. At the next level, the foreigner will learn radicals (including fake radicals = grapheme without meaning nor sound, but shared across several kanji) to make smarter mnemonics.
* The archaeologist way: learn the etymology of kanji (oracle bone style, bronze ware style, ten style, kyuji and shinji), then make educated guesses as to why they changed the way they did over time (bushu used as ideogram or phonogram, etc).

I now reached a point where I believe the following method to be the most efficient way of learning japanese is through jukugo:
1. Get a frequency list of jukugo and learn it through classical SRS system.
2. For each jukugo (eg `street 道 + path 路 = highway 道路`), learn its kanji by etymology, eg
      ![](https://i.imgur.com/p6MzPHU.png)
3. Reinforce that learning with a mnemonic using its biggest components (`A path 路 is paved with rocks to allow each 各 foot 足 to walk backwards`, both bushu are ideograms)
3. If you don't already know about a component, learn it with its radicals (eg `each 各 mouth 口 freezes during winter 夂`)
4. Whenever relatively frequent jukugo exist that use 2 kanji previously learnt, jump these jukugo to the top of the learning list to strengthen your knowledge on known kanji.

That's because learning all the kunyomi and onyomi independently is much harder and less useful than through vocabulary.

As of today, no tool exists that applies this methodology, and building such tool would obviously be a long and tedious task. 
Still, I should be able to hack something quickly for my personal usage and using existing tools (eg a script to filter jukugo, a memrise deck and the android kanji study app).
Sorry for this very long post. I simply found your repo and its [jukugo.txt](https://raw.githubusercontent.com/mifunetoshiro/kanjium/master/data/source_files/jukugo.txt) file, but it doesn't appear to be sorted by frequency. A frequency list would definitely be a plus for your ultimate kanji resource, do you think you can find it from somewhere ?

resources:
- [wiktionary 10,000 words](https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Japanese)
- [A 15,000 Japanese Word Frequency List](http://www.manythings.org/japanese/words/leeds/)

Thank you for your support. Also, any feedback on my thoughts will be appreciate. Who knows, if I find enough like-minded people, that project mentioned above could become a reality at some point

**Comment by mifunetoshiro** [comment]
Hi, the jukugo are not sorted by frequency, but they are from the list of around ~12,000 common/frequent jukugu found in EDICT, in 95% cases anyway. I only opted for a few examples for each kanji, as this was never meant to be a replacement for a full Japanese dictionary or something, only an extended kanji database, with a few word examples.
